# server
server:
  port: 8080

# mysql
mysql:
  host: 127.0.0.1
  port: 3306
  database: agriculture
  username: root
  password: Gen520

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db : 0

mqtt:
  host: broker.emqx.io
  port: 1883
  # username: genji
  # password: genji520
  username: Genji
  password: "1612977482"
  topic: "temp"

